# Generated by Django 6.0.1 on 2026-01-21 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('visibility', models.CharField(choices=[('PERSONAL', 'Personal'), ('TEAM', 'Team')], default='PERSONAL', max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=180, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('rrule', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='teams.team')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('DONE', 'Done')], default='UPCOMING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_cache', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='events.eventoccurrence')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrence_checklists', to='checklists.checklisttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_item_id', models.UUIDField(blank=True, null=True)),
                ('label_snapshot', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('unchecked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_checked', to=settings.AUTH_USER_MODEL)),
                ('occurrence_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.occurrencechecklist')),
                ('unchecked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_unchecked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='EventTemplateLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SETUP', 'Setup'), ('TEARDOWN', 'Teardown'), ('GENERIC', 'Generic')], default='GENERIC', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_links', to='events.event')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='checklists.checklisttemplate')),
            ],
            options={
                'unique_together': {('event', 'template', 'kind')},
            },
        ),
    ]
